### ISSUE TITLE
Fails to build with SFML 2.1

### ISSUE THREAD

**Issue by Mailaender** [thelaui/M.A.R.S.#13]
Tried to create an RPM for @openSUSE, but it fails to build with SFML version 2.1

```
[  246s] /home/abuild/rpmbuild/BUILD/mars-game/src/System/window.cpp: In function 'void window::draw(const sf::Drawable&, const sf::RenderStates&, sf::Shader*)':
[  246s] /home/abuild/rpmbuild/BUILD/mars-game/src/System/window.cpp:311:26: error: no matching function for call to 'sf::Shader::bind()'
[  246s]              shader->bind();
[  246s]                           ^
[  246s] /home/abuild/rpmbuild/BUILD/mars-game/src/System/window.cpp:311:26: note: candidate is:
[  246s] In file included from /usr/include/SFML/Graphics.hpp:41:0,
[  246s]                  from /home/abuild/rpmbuild/BUILD/mars-game/include/System/window.hpp:25,
[  246s]                  from /home/abuild/rpmbuild/BUILD/mars-game/src/System/window.cpp:18:
[  246s] /usr/include/SFML/Graphics/Shader.hpp:471:17: note: static void sf::Shader::bind(const sf::Shader*)
[  246s]      static void bind(const Shader* shader);

[  246s]                  ^
[  246s] /usr/include/SFML/Graphics/Shader.hpp:471:17: note:   candidate expects 1 argument, 0 provided
[  246s] /home/abuild/rpmbuild/BUILD/mars-game/src/System/window.cpp:316:21: error: 'class sf::Shader' has no member named 'unbind'
[  246s]              shader->unbind();
[  246s]                      ^
```

**Comment by eXpl0it3r** [comment]
Finally fixed with #2 🎉
